# Generated by Django 4.1.5 on 2023-02-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(max_length=50)),
                ('Cuit', models.PositiveIntegerField(blank=True)),
                ('Telefono', models.PositiveIntegerField(blank=True)),
                ('Correo', models.EmailField(max_length=25)),
                ('CS', models.BooleanField(default=False)),
                ('CN', models.BooleanField(default=False)),
                ('CP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(max_length=50)),
                ('Cuit', models.PositiveIntegerField(blank=True)),
                ('Telefono', models.PositiveIntegerField(blank=True)),
                ('Correo', models.EmailField(max_length=25)),
                ('CLocal', models.BooleanField()),
                ('CMedia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patente', models.CharField(max_length=10)),
                ('TipoUnidad', models.CharField(max_length=15)),
                ('Satelital', models.BooleanField()),
                ('Usuario', models.CharField(max_length=20)),
                ('Contrasena', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Unirte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Telefono', models.PositiveIntegerField(blank=True)),
                ('Correo', models.EmailField(max_length=25)),
            ],
        ),
    ]
